apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    g, alina, role:user-update
    p, role:user-update, accounts, update, *, allow
    p, role:user-update, account, get, *, allow
