apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd6
patches:
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: argocd-cm
    path: patches/argocd-cm.yaml
